# This file was generated by GoReleaser. DO NOT EDIT.
cask "terraci" do
  name "terraci"
  desc ""
  homepage "https://edelwud.github.io/terraci/"
  version "0.4.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terraci"
  manpage "manpages/terraci.1"
  manpage "manpages/terraci-completion.1"
  manpage "manpages/terraci-generate.1"
  manpage "manpages/terraci-graph.1"
  manpage "manpages/terraci-init.1"
  manpage "manpages/terraci-schema.1"
  manpage "manpages/terraci-validate.1"
  manpage "manpages/terraci-version.1"
  bash_completion "completions/terraci.bash"
  zsh_completion "completions/_terraci"
  fish_completion "completions/terraci.fish"

  on_macos do
    url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_darwin_all.tar.gz",
        verified: "github.com/edelwud/terraci"
    sha256 "f4d22d4e23bb09ee0bcb27fdb3ef8ebdc0b2e851eae3d23d93cec60e11af1251"
  end

  on_linux do
    on_intel do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_linux_amd64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "c361a2778500a88cd04b6d6af1c30c6602473405816411b1dc5d920338c1d1e7"
    end
    on_arm do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_linux_arm64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "2d184e3aaefc76759e20231bb4d5fddc0dd717a82bf4acc8ed8eaf86cfafd7f4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terraci"]
    end
  end

  # No zap stanza required
end
