# This file was generated by GoReleaser. DO NOT EDIT.
cask "terraci" do
  name "terraci"
  desc ""
  homepage "https://edelwud.github.io/terraci/"
  version "0.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terraci"
  manpage "manpages/terraci.1"
  manpage "manpages/terraci-*.1"
  bash_completion "completions/terraci.bash"
  zsh_completion "completions/_terraci"
  fish_completion "completions/terraci.fish"

  on_macos do
    on_intel do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_darwin_amd64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "1b00efe8217dbf5eff66659ce478d2d005f91eb00a5f51a1a0ac6e85b94bcc83"
    end
    on_arm do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_darwin_arm64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "8adcfb0b41b78d8fd6a0e92df35371fa224ae4ad5dcbdd52b0f5201fbb5bf226"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_linux_amd64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "964ea8ee403884c55ca5a0b9b65895f2c58615b651eb34ebe67f16115dfa3199"
    end
    on_arm do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_linux_arm64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "2470ee5d4bb3ac61a2b66299f6432088e59035a173c3a2f95d532d2b323c144c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terraci"]
    end
  end

  # No zap stanza required
end
