# This file was generated by GoReleaser. DO NOT EDIT.
cask "terraci" do
  version "0.7.1"

  on_macos do
    url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_darwin_all.tar.gz",
        verified: "github.com/edelwud/terraci"
    sha256 "61780e5e34a2b92e1748fc66f0067dbe6d89307485d8e712a1416b66c1dc6131"
    on_intel do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "e1d1dbd87eb3eda0ea81914aa04ef8a17fe31afb672fd587b3c79ef4c576c49b"
    end
    on_arm do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "33570cb8c8345ed0a5a172a6fa91c8df22da98ac945e2bd5e6e68f9c36f85c35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_linux_amd64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "61ec075c725a041d29083ea097a54a1c8e29efda0fe3cedfd1ca37a839bd23a4"
    end
    on_arm do
      url "https://github.com/edelwud/terraci/releases/download/v#{version}/terraci_#{version}_linux_arm64.tar.gz",
        verified: "github.com/edelwud/terraci"
      sha256 "9eae7490acac9743495f51925736a3789cb65a53c2d2df13f5fb67abcf1b7ad4"
    end
  end

  name "terraci"
  desc ""
  homepage "https://edelwud.github.io/terraci/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terraci"
  manpage "manpages/terraci-completion.1"
  manpage "manpages/terraci-generate.1"
  manpage "manpages/terraci-graph.1"
  manpage "manpages/terraci-init.1"
  manpage "manpages/terraci-schema.1"
  manpage "manpages/terraci-validate.1"
  manpage "manpages/terraci-version.1"
  manpage "manpages/terraci.1"
  manpage "manpages/xterraci-build.1"
  manpage "manpages/xterraci-list-plugins.1"
  manpage "manpages/xterraci-version.1"
  manpage "manpages/xterraci.1"
  bash_completion "completions/terraci.bash"
  fish_completion "completions/terraci.fish"
  zsh_completion "completions/_terraci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terraci"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xterraci"]
    end
  end

  # No zap stanza required

end
